export type BriefStepId =
  | "basics"
  | "purposeAudience"
  | "lookFeel"
  | "contentProduction"
  | "deliverablesTiming"
  | "summary";

export type ConfidenceState = "confident" | "guess" | "missing";

export type BriefFieldId =
  | "workingTitle"
  | "videoType"
  | "description"
  | "purpose"
  | "audience"
  | "feeling"
  | "referenceVideos"
  | "brandKit"
  | "liveFootage"
  | "voiceover"
  | "callToAction";

export type BriefFieldSource = "client_input" | "ai_inferred" | "manual_edit" | "missing";

export type BriefField = {
  id: BriefFieldId;
  label: string;
  value: string;
  confidence: ConfidenceState;
  source: BriefFieldSource;
  required: boolean;
};

export type BriefFields = Record<BriefFieldId, BriefField>;

export type ConfidenceChipModel = {
  state: ConfidenceState;
  label: "Confident" | "Guess" | "Missing";
  helper: string;
};

export type ChatMessage = {
  id: string;
  role: "client" | "ai";
  body: string;
  createdAt: string;
  attachments?: InputAttachment[];
  questionIndex?: number;
  questionTotal?: number;
  tone?: "intro" | "question" | "drafting";
};

export type InputAttachment = {
  id: string;
  kind: "document" | "link" | "reference_video";
  label: string;
  source: string;
};

export type Logline = {
  text: string;
  status: "not_generated" | "synced" | "out_of_sync";
  generatedFromMessageId?: string;
  lastRegeneratedAt?: string;
};

export type BriefDraft = {
  logline: string;
  fields: BriefFields;
};

export const briefSteps: Array<{ id: BriefStepId; index: number; label: string; shortLabel: string }> = [
  { id: "basics", index: 1, label: "The basics", shortLabel: "Basics" },
  { id: "purposeAudience", index: 2, label: "Purpose and audience", shortLabel: "Purpose" },
  { id: "lookFeel", index: 3, label: "Look and feel", shortLabel: "Look" },
  { id: "contentProduction", index: 4, label: "Content and production", shortLabel: "Content" },
  { id: "deliverablesTiming", index: 5, label: "Deliverables and timing", shortLabel: "Timing" },
  { id: "summary", index: 6, label: "Brief Summary", shortLabel: "Summary" },
];

export const confidenceChipLabels: Record<ConfidenceState, ConfidenceChipModel> = {
  confident: {
    state: "confident",
    label: "Confident",
    helper: "Confirmed from input or a manual edit.",
  },
  guess: {
    state: "guess",
    label: "Guess",
    helper: "AI-inferred. Click to confirm.",
  },
  missing: {
    state: "missing",
    label: "Missing",
    helper: "Required before approval.",
  },
};

export type BriefVideoTypeDetail = {
  name: string;
  summary: string;
  description: string;
};

export const briefVideoTypeDetails: BriefVideoTypeDetail[] = [
  {
    name: "Animation",
    summary: "Motion graphics or character-led video for abstract ideas and complex processes.",
    description:
      "Motion graphics or character-driven video, made frame by frame or in software. Great for abstract ideas, complex processes, or when you want a playful, distinctive look that live action can't give you. Anything is possible - which is the fun and the trap.",
  },
  {
    name: "AI Video",
    summary: "AI-generated scenes or image animation for stylised, fast-turnaround work.",
    description:
      "Video generated by AI tools, from still-image animation to fully synthesised scenes. Fast, cheap, and useful when you don't have the budget for a shoot or want a surreal look. Quality varies wildly, so it's best for stylised or short-form work rather than anything that needs to feel completely real.",
  },
  {
    name: "Brand Film",
    summary: "A cinematic hero piece about who the company is and what it stands for.",
    description:
      "A cinematic, emotion-first film about who the company is and what it stands for. Usually a hero piece for a website, launch, or funding round. Big feel, high craft, memorable in one watch. Done well, it can carry a brand for years.",
  },
  {
    name: "Case Study / Testimonial",
    summary: "Real customers explaining, in their own words, how something helped them.",
    description:
      "Real customers, in their own words, telling the story of how something helped them. The most trusted format in B2B and nonprofit video. Interview-led, backed with B-roll of them in their world. Honest beats polished every time.",
  },
  {
    name: "Commercial / TVC",
    summary: "Broadcast-style advertising for TV, streaming, or paid social.",
    description:
      "Broadcast-style ads for TV, streaming, or paid social. Highly produced, tightly scripted, built to sell in 15 to 60 seconds. Big idea in the first three seconds, memorable last frame, clear call to action. The bar for craft is high.",
  },
  {
    name: "Documentary",
    summary: "Long-form storytelling built around real people, events, or ideas.",
    description:
      "Long-form storytelling built around real people, events, or ideas. Slow to make, but deeply moving when it works. Great for nonprofits, campaigns, or brands with a genuine story to tell. Not a format for a rushed timeline.",
  },
  {
    name: "Event",
    summary: "Promoting, livestreaming, or recapping a conference, launch, or community moment.",
    description:
      "Promoting, livestreaming, or recapping an event - conferences, launches, community moments. Fast turnaround, energetic edit, made to sell the next one. Highlights reels usually cut same-week or same-day.",
  },
  {
    name: "Explainer",
    summary: "A clear, focused video explaining a product, service, or idea.",
    description:
      "Clear, focused video explaining a product, service, or idea in a couple of minutes. Great for websites, pitch decks, and sales support. Structured, calm, easy to follow. Often animated, but works in live action too.",
  },
  {
    name: "Fashion / Lookbook",
    summary: "Style-first video for collections, drops, or a season's mood.",
    description:
      "Style-first video showcasing collections, drops, or a season's mood. Music-led, minimal dialogue, heavy on visual craft. Cut to loop on social or lead a lookbook page.",
  },
  {
    name: "Internal Comms",
    summary: "Video made for your own team, from updates to onboarding and culture pieces.",
    description:
      "Video made for your own team - all-hands updates, culture pieces, onboarding, town halls. Less polished than external work, more honest. Real leaders, real language, straight to the point.",
  },
  {
    name: "Live Action",
    summary: "Camera-led video with performers, presenters, experts, or actors.",
    description:
      "Any video that requires a camera and a performer. It could be a piece to camera - a great way to put a face to the organisation, and create a direct link between, say, a founder and their audience. Or it can be for interviewing experts and simplifying their thoughts. You could also do scripted videos with actors, like a comedy. Social media is a crowded place, and acted videos can be a good way to cut through - but be careful, it's hard to do well.",
  },
  {
    name: "Music Video",
    summary: "Music-first video where rhythm, texture, and image carry the piece.",
    description:
      "Music-first video for artists, bands, or releases. Rhythm, texture, and image over story. Wide creative range - narrative, performance, abstract, or all three. Budget varies enormously but the best ones make the song feel bigger.",
  },
  {
    name: "Podcast",
    summary: "Audio-first or filmed episodes for regular publishing and social cutdowns.",
    description:
      "Audio-first or fully filmed podcast episodes, built for regular publishing. Multi-cam setups, clean audio, minimal editing. Great for building an audience over time or repurposing into short-form clips for social.",
  },
  {
    name: "Product / Demo",
    summary: "Shows what the product does, how it looks, and why it matters.",
    description:
      "Shows the product in action - what it does, how it looks, why it matters. Feature-focused, tightly scripted, often shot in-hand or on-screen. Great for websites, app stores, and sales enablement.",
  },
  {
    name: "Real Estate",
    summary: "Property showcases for sale, rent, portfolio, or campaign use.",
    description:
      "Property showcases for sale, rent, or portfolio use. Steady, well-lit, walk-through filming that helps buyers see themselves in the space. Drone shots for exteriors, gimbal for interiors, edited to flow room to room.",
  },
  {
    name: "Short-Form / Reels",
    summary: "Vertical short-form for TikTok, Instagram Reels, and YouTube Shorts.",
    description:
      "Vertical short-form for TikTok, Instagram Reels, and YouTube Shorts. 15 to 60 seconds, hook in the first second, native to the platform. Made in volume, tested fast, built for the algorithm.",
  },
  {
    name: "Training / How To",
    summary: "Instructional video that teaches a skill, workflow, or process.",
    description:
      "Instructional video that teaches a skill or process. Clear steps, close-ups on what matters, screen recording where useful. Made once, watched many times. Structure and clarity win over style.",
  },
  {
    name: "Wedding / Events",
    summary: "Personal event films for weddings, milestones, and celebrations.",
    description:
      "Personal event films - weddings, milestones, celebrations. Emotional, story-led, cut to music that means something to the people in it. High craft on a personal scale.",
  },
];

export const briefVideoTypes = briefVideoTypeDetails.map((videoType) => videoType.name);

export const initialBriefFields: BriefFields = {
  workingTitle: {
    id: "workingTitle",
    label: "Working title",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  videoType: {
    id: "videoType",
    label: "Video type",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  description: {
    id: "description",
    label: "Description",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  purpose: {
    id: "purpose",
    label: "Purpose",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  audience: {
    id: "audience",
    label: "Who's this video for?",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  feeling: {
    id: "feeling",
    label: "What is the tone?",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  referenceVideos: {
    id: "referenceVideos",
    label: "Any similar videos that already exist?",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  brandKit: {
    id: "brandKit",
    label: "Which brand kit should we use?",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  liveFootage: {
    id: "liveFootage",
    label: "Live footage",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  voiceover: {
    id: "voiceover",
    label: "Do you want a voiceover?",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
  callToAction: {
    id: "callToAction",
    label: "What do we want them to do next? (Call To Action)",
    value: "",
    confidence: "missing",
    source: "missing",
    required: true,
  },
};

export const initialChatMessages: ChatMessage[] = [
  {
    id: "brief-ai-welcome",
    role: "ai",
    body: "Tell me what you are making. Paste notes, links or reference videos and I will ask a few questions before drafting the basics.",
    createdAt: "Now",
  },
];

export const briefClarifyingQuestions = [
  "Who is the main audience for this video?",
  "Do you have any stimulus material or uploads to share? The more you share, the smarter your brief. Drop in scripts, meeting notes, mood boards, reference videos - anything you've got.",
  "What must the video say or include, and is there anything we should avoid?",
] as const;

export const fallbackBriefDraft: BriefDraft = {
  logline:
    "A clear customer-facing film that turns the project promise into a concise story for the right audience.",
  fields: {
    workingTitle: {
      id: "workingTitle",
      label: "Working title",
      value: "Sales Narrative",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    videoType: {
      id: "videoType",
      label: "Video type",
      value: "Brand Film",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    description: {
      id: "description",
      label: "Description",
      value:
        "A polished brand film for a customer-facing launch. The video should introduce the product promise, show the problem in plain language, and make the sales story feel useful, credible and easy to repeat.",
      confidence: "confident",
      source: "client_input",
      required: true,
    },
    purpose: {
      id: "purpose",
      label: "Purpose",
      value: "Awareness - Make more people know about your topic",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    audience: {
      id: "audience",
      label: "Who's this video for?",
      value: "Existing customers and prospective buyers who need a fast, plain-language overview before taking the next step.",
      confidence: "confident",
      source: "client_input",
      required: true,
    },
    feeling: {
      id: "feeling",
      label: "What is the tone?",
      value: "Informative, Urgent",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    referenceVideos: {
      id: "referenceVideos",
      label: "Any similar videos that already exist?",
      value: "",
      confidence: "missing",
      source: "missing",
      required: true,
    },
    brandKit: {
      id: "brandKit",
      label: "Which brand kit should we use?",
      value: "House kit",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    liveFootage: {
      id: "liveFootage",
      label: "Live footage",
      value: "Use existing",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    voiceover: {
      id: "voiceover",
      label: "Do you want a voiceover?",
      value: "No, or we'll do our own",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
    callToAction: {
      id: "callToAction",
      label: "What do we want them to do next? (Call To Action)",
      value: "Book a session",
      confidence: "guess",
      source: "ai_inferred",
      required: true,
    },
  },
};

export const briefDraftOptions: Array<{ keywords: string[]; draft: BriefDraft }> = [
  {
    keywords: ["payday", "super", "employer", "cbus"],
    draft: {
      logline:
        "A short, confident employer education video that makes Payday Super feel simple, timely and worth acting on.",
      fields: {
        workingTitle: {
          id: "workingTitle",
          label: "Working title",
          value: "Employer Education",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        videoType: {
          id: "videoType",
          label: "Video type",
          value: "Short-form / Reels",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        description: {
          id: "description",
          label: "Description",
          value:
            "A short educational video for employer audiences about the upcoming Payday Super changes. It should feel natural and relaxed, use a presenter-led style, and direct viewers to the campaign landing page for next steps.",
          confidence: "confident",
          source: "client_input",
          required: true,
        },
        purpose: {
          id: "purpose",
          label: "Purpose",
          value: "Education - Explain clearly",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        audience: {
          id: "audience",
          label: "Who's this video for?",
          value: "Employers and payroll decision-makers preparing for Payday Super.",
          confidence: "confident",
          source: "client_input",
          required: true,
        },
        feeling: {
          id: "feeling",
          label: "What is the tone?",
          value: "Informative",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        referenceVideos: {
          id: "referenceVideos",
          label: "Any similar videos that already exist?",
          value: "",
          confidence: "missing",
          source: "missing",
          required: true,
        },
        brandKit: {
          id: "brandKit",
          label: "Which brand kit should we use?",
          value: "House kit",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        liveFootage: {
          id: "liveFootage",
          label: "Live footage",
          value: "Shoot new|ChopChop shoots",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        voiceover: {
          id: "voiceover",
          label: "Do you want a voiceover?",
          value: "No, or we'll do our own",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        callToAction: {
          id: "callToAction",
          label: "What do we want them to do next? (Call To Action)",
          value: "Learn more",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
      },
    },
  },
  {
    keywords: ["health", "care", "clinic", "family", "maya"],
    draft: {
      logline:
        "A warm care story that shows how Harbour Health turns complex decisions into a calm, guided path for families.",
      fields: {
        workingTitle: {
          id: "workingTitle",
          label: "Working title",
          value: "Care Journey",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        videoType: {
          id: "videoType",
          label: "Video type",
          value: "Documentary",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        description: {
          id: "description",
          label: "Description",
          value:
            "A human documentary-style film showing how Harbour Health helps families navigate care decisions. The video should centre on Maya, a nurse guiding people through the plan, the paperwork and the handover moments that build trust.",
          confidence: "confident",
          source: "client_input",
          required: true,
        },
        purpose: {
          id: "purpose",
          label: "Purpose",
          value: "Awareness - Make more people know about your topic",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        audience: {
          id: "audience",
          label: "Who's this video for?",
          value: "Families comparing care options for someone they love.",
          confidence: "confident",
          source: "client_input",
          required: true,
        },
        feeling: {
          id: "feeling",
          label: "What is the tone?",
          value: "Inspirational",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        referenceVideos: {
          id: "referenceVideos",
          label: "Any similar videos that already exist?",
          value: "",
          confidence: "missing",
          source: "missing",
          required: true,
        },
        brandKit: {
          id: "brandKit",
          label: "Which brand kit should we use?",
          value: "House kit",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        liveFootage: {
          id: "liveFootage",
          label: "Live footage",
          value: "Shoot new|ChopChop shoots",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        voiceover: {
          id: "voiceover",
          label: "Do you want a voiceover?",
          value: "No, or we'll do our own",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
        callToAction: {
          id: "callToAction",
          label: "What do we want them to do next? (Call To Action)",
          value: "Contact us",
          confidence: "guess",
          source: "ai_inferred",
          required: true,
        },
      },
    },
  },
];

export const fieldRegenerationValues: Record<BriefFieldId, string[]> = {
  workingTitle: [
    "Sales Narrative",
    "Guided Launch",
    "Clearer Next Steps",
  ],
  videoType: ["Brand Film", "Explainer", "Case Study / Testimonial", "Product / Demo"],
  description: [
    "A concise brand film that introduces the campaign, names the customer problem and gives the audience a clear reason to act.",
    "A customer-facing film that combines plain-language explanation with a polished visual rhythm suited to sales and launch channels.",
    "A short project brief for a confident video that turns scattered source notes into one useful story for customers.",
  ],
  purpose: [
    "Awareness - Make more people know about your topic",
    "Education - Explain clearly",
    "Engagement - Build and energise community",
  ],
  audience: [
    "Existing customers and prospective buyers who need a clear, plain-language overview.",
    "Decision-makers who are interested but need enough context to act with confidence.",
    "The main audience described in the client brief and clarifying answers.",
  ],
  feeling: [
    "Informative, Urgent",
    "Inspirational, Emotional / Moving",
    "Corporate / Professional, Powerful",
  ],
  referenceVideos: [
    "",
    "",
    "",
  ],
  brandKit: [
    "House kit",
    "Client kit - Nike",
    "Minimal kit",
  ],
  liveFootage: [
    "Use existing",
    "Shoot new|ChopChop shoots",
    "Shoot new|You shoot",
  ],
  voiceover: [
    "No, or we'll do our own",
    "Yes|Male voiceover|Alex",
    "Yes|Female voiceover|Kai",
  ],
  callToAction: [
    "Book a session",
    "Learn more",
    "Contact us",
  ],
};
